name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@6fb5d7162863b67cd1e006b2262db7da78608c88
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
